### ISSUE TITLE
Please specify a license

### ISSUE THREAD

**Issue by Hexstream** [40ants/mailgun#1]
The awesome-cl list notes that your project does not specify a license.

As always, I strongly recommend [the Unlicense](https://unlicense.org/), but any sane license will do...

**Comment by svetlyak40wt** [comment]
Good Idea! I'll add it right now.

I  like the idea of the Unlicense!

**Comment by Hexstream** [comment]
Wonderful!! I've been using it systematically for all my projects (except
CLHS ASDF wrapper) since basically forever!

**Comment by svetlyak40wt** [comment]
Done.

**Comment by Hexstream** [comment]
Perfect! Consider upgrading the link to https.
